// node scripts/write-sample-catalog.ts: lists the VCSL grand piano samples at the pinned commit,
// downloads the first PREFIX_SECONDS of each, and writes their sizes and SHA-256 to
// src/samples/piano-catalog.ts. Needs the network; run it only when the pinned commit or the
// prefix length changes.
import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { midiToFrequency, pitchToMidi } from "../src/pitch.ts";
import { decodeWavMono, readWavLayout } from "../src/samples/wav-read.ts";
import { PIANO_DIR, PIANO_FILE, pianoFile, PREFIX_SECONDS, VCSL_COMMIT, VCSL_REPO, vcslUrl, type CatalogEntry } from "../src/samples/vcsl.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TreeSchema = z.object({ truncated: z.boolean(), tree: z.array(z.object({ path: z.string(), type: z.string() })) });

async function range(url: string, end: number): Promise<Uint8Array> {
  const response = await fetch(url, { headers: { Range: `bytes=0-${end - 1}` } });
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return new Uint8Array(await response.arrayBuffer()).subarray(0, end);
}

/** Strongest frequency within ±3 % of `near` (Hann-windowed DFT on a 0.1-cent grid). */
function dominant(x: Float32Array, rate: number, near: number): number {
  let best = 0;
  let bestF = near;
  for (let f = near * 0.97; f <= near * 1.03; f += near / 20000) {
    let re = 0;
    let im = 0;
    for (let i = 0; i < x.length; i++) {
      const w = (0.5 - 0.5 * Math.cos((2 * Math.PI * i) / (x.length - 1))) * (x[i] ?? 0);
      re += w * Math.cos((2 * Math.PI * f * i) / rate);
      im += w * Math.sin((2 * Math.PI * f * i) / rate);
    }
    if (Math.hypot(re, im) > best) [best, bestF] = [Math.hypot(re, im), f];
  }
  return bestF;
}

/**
 * How far a sample is from equal temperament, in cents, measured from 0.2 to 2.2 s: on the
 * fundamental, or in the bass, where the fundamental is weak, on the 2nd (below 100 Hz) or 3rd
 * (below 50 Hz) partial — the ones the ear goes by.
 */
function centsOff(prefix: Uint8Array, pitch: string): number {
  const { data, sampleRate } = decodeWavMono(prefix);
  const f = midiToFrequency(pitchToMidi(pitch) ?? 69);
  let k = 1;
  if (f < 100) k = f < 50 ? 3 : 2;
  const measured = dominant(data.subarray(Math.round(0.2 * sampleRate), Math.round(2.2 * sampleRate)), sampleRate, k * f);
  return Math.round(12000 * Math.log2(measured / (k * f))) / 10;
}

async function entryOf(file: string, pitch: string, layer: number): Promise<CatalogEntry> {
  const url = vcslUrl(`${PIANO_DIR}/${file}`);
  const layout = readWavLayout(await range(url, 4096));
  const frameBytes = (layout.bits / 8) * layout.channels;
  const bytes = layout.dataOffset + Math.min(layout.dataBytes, Math.round(PREFIX_SECONDS * layout.sampleRate) * frameBytes);
  const prefix = await range(url, bytes);
  if (prefix.length !== bytes) throw new Error(`${file}: got ${prefix.length} bytes, expected ${bytes}`);
  return { pitch, layer, file, bytes, sha256: createHash("sha256").update(prefix).digest("hex"), cents: centsOff(prefix, pitch) };
}

const response = await fetch(`https://api.github.com/repos/${VCSL_REPO}/git/trees/${VCSL_COMMIT}?recursive=1`);
const tree = TreeSchema.parse(await response.json());
if (tree.truncated) throw new Error("GitHub truncated the tree listing");
const files = tree.tree
  .filter((item) => item.type === "blob" && item.path.startsWith(`${PIANO_DIR}/`))
  .map((item) => item.path.slice(PIANO_DIR.length + 1))
  .flatMap((file) => {
    const match = PIANO_FILE.exec(file);
    return match?.[1] === undefined || match[2] === undefined ? [] : [{ file, pitch: match[1], layer: Number(match[2]) }];
  });

const entries: CatalogEntry[] = [];
for (let i = 0; i < files.length; i += 8) {
  entries.push(...(await Promise.all(files.slice(i, i + 8).map((f) => entryOf(f.file, f.pitch, f.layer)))));
  console.log(`${entries.length}/${files.length}`);
}
entries.sort((a, b) => a.file.localeCompare(b.file));
const unexpected = entries.filter((e) => e.file !== pianoFile(e.pitch, e.layer));
if (unexpected.length > 0) throw new Error(`file names no longer follow pianoFile(): ${unexpected[0]?.file}`);
const rows = entries.map((e) => `  ${JSON.stringify([e.pitch, e.layer, e.bytes, e.sha256, e.cents])},`).join("\n");

const text = `// Generated by scripts/write-sample-catalog.ts — do not edit. VCSL ${VCSL_COMMIT.slice(0, 12)}, ${PIANO_DIR}.
import type { CatalogRow } from "./vcsl.ts";

export const PIANO_CATALOG: readonly CatalogRow[] = [
${rows}
];
`;
await writeFile(join(root, "src/samples/piano-catalog.ts"), text);
console.log(`wrote src/samples/piano-catalog.ts (${entries.length} samples, ${(entries.reduce((s, e) => s + e.bytes, 0) / 1e6).toFixed(1)} MB in all)`);
